import json

def get_visa_data():
    return [
        {"subclass_number": "189", "visa_name": "Skilled Independent", "stream_name": "Points-tested", "category": "Permanent", "base_cost_aud": 4710.00, "points_tested": True, "requires_sponsor": False},
        {"subclass_number": "189", "visa_name": "Skilled Independent", "stream_name": "New Zealand", "category": "Permanent", "base_cost_aud": 4710.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "190", "visa_name": "Skilled Nominated", "stream_name": "State Nominated", "category": "Permanent", "base_cost_aud": 4710.00, "points_tested": True, "requires_sponsor": False},
        {"subclass_number": "491", "visa_name": "Skilled Work Regional (Provisional)", "stream_name": "State/Territory Sponsored", "category": "Provisional", "base_cost_aud": 4710.00, "points_tested": True, "requires_sponsor": False},
        {"subclass_number": "491", "visa_name": "Skilled Work Regional (Provisional)", "stream_name": "Family Sponsored", "category": "Provisional", "base_cost_aud": 4710.00, "points_tested": True, "requires_sponsor": True},
        {"subclass_number": "482", "visa_name": "Temporary Skill Shortage", "stream_name": "Short-term", "category": "Temporary", "base_cost_aud": 1495.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "482", "visa_name": "Temporary Skill Shortage", "stream_name": "Medium-term", "category": "Temporary", "base_cost_aud": 3115.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "482", "visa_name": "Temporary Skill Shortage", "stream_name": "Labour Agreement", "category": "Temporary", "base_cost_aud": 3115.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "186", "visa_name": "Employer Nomination Scheme", "stream_name": "Direct Entry", "category": "Permanent", "base_cost_aud": 4710.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "186", "visa_name": "Employer Nomination Scheme", "stream_name": "Temporary Residence Transition", "category": "Permanent", "base_cost_aud": 4710.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "186", "visa_name": "Employer Nomination Scheme", "stream_name": "Labour Agreement", "category": "Permanent", "base_cost_aud": 4710.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "494", "visa_name": "Skilled Employer Sponsored Regional (Provisional)", "stream_name": "Employer Sponsored", "category": "Provisional", "base_cost_aud": 4710.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "494", "visa_name": "Skilled Employer Sponsored Regional (Provisional)", "stream_name": "Labour Agreement", "category": "Provisional", "base_cost_aud": 4710.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "820", "visa_name": "Partner (Temporary)", "stream_name": "Onshore", "category": "Provisional", "base_cost_aud": 9095.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "801", "visa_name": "Partner (Permanent)", "stream_name": "Onshore", "category": "Permanent", "base_cost_aud": 0.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "309", "visa_name": "Partner (Provisional)", "stream_name": "Offshore", "category": "Provisional", "base_cost_aud": 9095.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "100", "visa_name": "Partner (Migrant)", "stream_name": "Offshore", "category": "Permanent", "base_cost_aud": 0.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "300", "visa_name": "Prospective Marriage", "stream_name": "Offshore", "category": "Provisional", "base_cost_aud": 9095.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "500", "visa_name": "Student", "stream_name": "Higher Education", "category": "Temporary", "base_cost_aud": 710.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "500", "visa_name": "Student", "stream_name": "VET", "category": "Temporary", "base_cost_aud": 710.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "500", "visa_name": "Student", "stream_name": "ELICOS", "category": "Temporary", "base_cost_aud": 710.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "500", "visa_name": "Student", "stream_name": "Schools", "category": "Temporary", "base_cost_aud": 710.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "500", "visa_name": "Student", "stream_name": "Non-Award", "category": "Temporary", "base_cost_aud": 710.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "500", "visa_name": "Student", "stream_name": "Postgraduate Research", "category": "Temporary", "base_cost_aud": 710.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "590", "visa_name": "Student Guardian", "stream_name": "Guardian", "category": "Temporary", "base_cost_aud": 710.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "485", "visa_name": "Temporary Graduate", "stream_name": "Post-Study Work", "category": "Temporary", "base_cost_aud": 1895.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "485", "visa_name": "Temporary Graduate", "stream_name": "Graduate Work", "category": "Temporary", "base_cost_aud": 1895.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "485", "visa_name": "Temporary Graduate", "stream_name": "Second Post-Study Work", "category": "Temporary", "base_cost_aud": 745.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "600", "visa_name": "Visitor", "stream_name": "Tourist (Onshore)", "category": "Temporary", "base_cost_aud": 425.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "600", "visa_name": "Visitor", "stream_name": "Tourist (Offshore)", "category": "Temporary", "base_cost_aud": 195.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "600", "visa_name": "Visitor", "stream_name": "Sponsored Family", "category": "Temporary", "base_cost_aud": 195.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "600", "visa_name": "Visitor", "stream_name": "Business Visitor", "category": "Temporary", "base_cost_aud": 195.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "600", "visa_name": "Visitor", "stream_name": "Approved Destination Status", "category": "Temporary", "base_cost_aud": 195.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "600", "visa_name": "Visitor", "stream_name": "Frequent Traveller", "category": "Temporary", "base_cost_aud": 1395.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "651", "visa_name": "eVisitor", "stream_name": "eVisitor", "category": "Temporary", "base_cost_aud": 0.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "601", "visa_name": "Electronic Travel Authority", "stream_name": "ETA", "category": "Temporary", "base_cost_aud": 20.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "417", "visa_name": "Working Holiday", "stream_name": "Working Holiday", "category": "Temporary", "base_cost_aud": 635.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "462", "visa_name": "Work and Holiday", "stream_name": "Work and Holiday", "category": "Temporary", "base_cost_aud": 635.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "408", "visa_name": "Temporary Activity", "stream_name": "Special Program", "category": "Temporary", "base_cost_aud": 405.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "408", "visa_name": "Temporary Activity", "stream_name": "Religious Work", "category": "Temporary", "base_cost_aud": 405.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "408", "visa_name": "Temporary Activity", "stream_name": "Research", "category": "Temporary", "base_cost_aud": 405.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "408", "visa_name": "Temporary Activity", "stream_name": "Invited Participant", "category": "Temporary", "base_cost_aud": 405.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "408", "visa_name": "Temporary Activity", "stream_name": "Sporting", "category": "Temporary", "base_cost_aud": 405.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "408", "visa_name": "Temporary Activity", "stream_name": "Entertainment", "category": "Temporary", "base_cost_aud": 405.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "408", "visa_name": "Temporary Activity", "stream_name": "Superyacht Crew", "category": "Temporary", "base_cost_aud": 405.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "408", "visa_name": "Temporary Activity", "stream_name": "Exchange", "category": "Temporary", "base_cost_aud": 405.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "408", "visa_name": "Temporary Activity", "stream_name": "Australian Government Endorsed Event", "category": "Temporary", "base_cost_aud": 405.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "408", "visa_name": "Temporary Activity", "stream_name": "Domestic Worker (Executive)", "category": "Temporary", "base_cost_aud": 405.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "400", "visa_name": "Temporary Work (Short Stay Specialist)", "stream_name": "Highly Specialised Work", "category": "Temporary", "base_cost_aud": 405.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "403", "visa_name": "Temporary Work (International Relations)", "stream_name": "Government Agreement", "category": "Temporary", "base_cost_aud": 405.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "403", "visa_name": "Temporary Work (International Relations)", "stream_name": "Foreign Government Agency", "category": "Temporary", "base_cost_aud": 405.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "403", "visa_name": "Temporary Work (International Relations)", "stream_name": "Domestic Worker (Diplomatic or Consular)", "category": "Temporary", "base_cost_aud": 405.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "403", "visa_name": "Temporary Work (International Relations)", "stream_name": "Privileges and Immunities", "category": "Temporary", "base_cost_aud": 0.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "403", "visa_name": "Temporary Work (International Relations)", "stream_name": "Pacific Australia Labour Mobility", "category": "Temporary", "base_cost_aud": 0.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "407", "visa_name": "Training", "stream_name": "Occupational Training", "category": "Temporary", "base_cost_aud": 405.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "188", "visa_name": "Business Innovation and Investment (Provisional)", "stream_name": "Business Innovation", "category": "Provisional", "base_cost_aud": 6270.00, "points_tested": True, "requires_sponsor": False},
        {"subclass_number": "188", "visa_name": "Business Innovation and Investment (Provisional)", "stream_name": "Investor", "category": "Provisional", "base_cost_aud": 6270.00, "points_tested": True, "requires_sponsor": False},
        {"subclass_number": "188", "visa_name": "Business Innovation and Investment (Provisional)", "stream_name": "Significant Investor", "category": "Provisional", "base_cost_aud": 9455.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "188", "visa_name": "Business Innovation and Investment (Provisional)", "stream_name": "Premium Investor", "category": "Provisional", "base_cost_aud": 10255.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "188", "visa_name": "Business Innovation and Investment (Provisional)", "stream_name": "Entrepreneur", "category": "Provisional", "base_cost_aud": 4240.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "888", "visa_name": "Business Innovation and Investment (Permanent)", "stream_name": "Business Innovation", "category": "Permanent", "base_cost_aud": 3025.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "888", "visa_name": "Business Innovation and Investment (Permanent)", "stream_name": "Investor", "category": "Permanent", "base_cost_aud": 3025.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "888", "visa_name": "Business Innovation and Investment (Permanent)", "stream_name": "Significant Investor", "category": "Permanent", "base_cost_aud": 3025.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "888", "visa_name": "Business Innovation and Investment (Permanent)", "stream_name": "Premium Investor", "category": "Permanent", "base_cost_aud": 3025.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "888", "visa_name": "Business Innovation and Investment (Permanent)", "stream_name": "Entrepreneur", "category": "Permanent", "base_cost_aud": 3025.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "132", "visa_name": "Business Talent (Permanent)", "stream_name": "Significant Business History", "category": "Permanent", "base_cost_aud": 7855.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "132", "visa_name": "Business Talent (Permanent)", "stream_name": "Venture Capital Entrepreneur", "category": "Permanent", "base_cost_aud": 7855.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "858", "visa_name": "Global Talent", "stream_name": "Global Talent", "category": "Permanent", "base_cost_aud": 4305.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "124", "visa_name": "Distinguished Talent", "stream_name": "Distinguished Talent", "category": "Permanent", "base_cost_aud": 4305.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "143", "visa_name": "Contributory Parent", "stream_name": "Contributory Parent", "category": "Permanent", "base_cost_aud": 47975.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "173", "visa_name": "Contributory Parent (Temporary)", "stream_name": "Contributory Parent", "category": "Temporary", "base_cost_aud": 32340.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "864", "visa_name": "Contributory Aged Parent", "stream_name": "Contributory Aged Parent", "category": "Permanent", "base_cost_aud": 47975.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "884", "visa_name": "Contributory Aged Parent (Temporary)", "stream_name": "Contributory Aged Parent", "category": "Temporary", "base_cost_aud": 32340.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "103", "visa_name": "Parent", "stream_name": "Parent", "category": "Permanent", "base_cost_aud": 4990.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "804", "visa_name": "Aged Parent", "stream_name": "Aged Parent", "category": "Permanent", "base_cost_aud": 4990.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "870", "visa_name": "Sponsored Parent (Temporary)", "stream_name": "Sponsored Parent", "category": "Temporary", "base_cost_aud": 5735.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "101", "visa_name": "Child", "stream_name": "Child", "category": "Permanent", "base_cost_aud": 3055.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "802", "visa_name": "Child", "stream_name": "Child", "category": "Permanent", "base_cost_aud": 3055.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "102", "visa_name": "Adoption", "stream_name": "Adoption", "category": "Permanent", "base_cost_aud": 3055.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "445", "visa_name": "Dependent Child", "stream_name": "Dependent Child", "category": "Temporary", "base_cost_aud": 3055.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "114", "visa_name": "Aged Dependent Relative", "stream_name": "Aged Dependent Relative", "category": "Permanent", "base_cost_aud": 4990.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "838", "visa_name": "Aged Dependent Relative", "stream_name": "Aged Dependent Relative", "category": "Permanent", "base_cost_aud": 4990.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "115", "visa_name": "Remaining Relative", "stream_name": "Remaining Relative", "category": "Permanent", "base_cost_aud": 4990.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "835", "visa_name": "Remaining Relative", "stream_name": "Remaining Relative", "category": "Permanent", "base_cost_aud": 4990.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "116", "visa_name": "Carer", "stream_name": "Carer", "category": "Permanent", "base_cost_aud": 4990.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "836", "visa_name": "Carer", "stream_name": "Carer", "category": "Permanent", "base_cost_aud": 4990.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "117", "visa_name": "Orphan Relative", "stream_name": "Orphan Relative", "category": "Permanent", "base_cost_aud": 1810.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "837", "visa_name": "Orphan Relative", "stream_name": "Orphan Relative", "category": "Permanent", "base_cost_aud": 1810.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "151", "visa_name": "Former Resident", "stream_name": "Former Resident", "category": "Permanent", "base_cost_aud": 4240.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "155", "visa_name": "Resident Return", "stream_name": "Resident Return", "category": "Permanent", "base_cost_aud": 465.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "157", "visa_name": "Resident Return", "stream_name": "Resident Return", "category": "Permanent", "base_cost_aud": 465.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "159", "visa_name": "Provisional Resident Return", "stream_name": "Provisional Resident Return", "category": "Provisional", "base_cost_aud": 420.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "461", "visa_name": "New Zealand Citizen Family Relationship (Temporary)", "stream_name": "New Zealand Citizen Family Relationship", "category": "Temporary", "base_cost_aud": 405.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "444", "visa_name": "Special Category", "stream_name": "Special Category", "category": "Temporary", "base_cost_aud": 0.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "010", "visa_name": "Bridging visa A", "stream_name": "BVA", "category": "Temporary", "base_cost_aud": 0.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "020", "visa_name": "Bridging visa B", "stream_name": "BVB", "category": "Temporary", "base_cost_aud": 180.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "030", "visa_name": "Bridging visa C", "stream_name": "BVC", "category": "Temporary", "base_cost_aud": 0.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "040", "visa_name": "Bridging visa D", "stream_name": "BVD", "category": "Temporary", "base_cost_aud": 0.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "041", "visa_name": "Bridging visa D", "stream_name": "BVD", "category": "Temporary", "base_cost_aud": 0.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "050", "visa_name": "Bridging visa E", "stream_name": "BVE", "category": "Temporary", "base_cost_aud": 0.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "051", "visa_name": "Bridging visa E", "stream_name": "BVE", "category": "Temporary", "base_cost_aud": 0.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "060", "visa_name": "Bridging visa F", "stream_name": "BVF", "category": "Temporary", "base_cost_aud": 0.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "771", "visa_name": "Transit", "stream_name": "Transit", "category": "Temporary", "base_cost_aud": 0.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "988", "visa_name": "Maritime Crew", "stream_name": "Maritime Crew", "category": "Temporary", "base_cost_aud": 0.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "200", "visa_name": "Refugee", "stream_name": "Refugee", "category": "Permanent", "base_cost_aud": 0.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "201", "visa_name": "In-country Special Humanitarian", "stream_name": "In-country Special Humanitarian", "category": "Permanent", "base_cost_aud": 0.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "202", "visa_name": "Global Special Humanitarian", "stream_name": "Global Special Humanitarian", "category": "Permanent", "base_cost_aud": 0.00, "points_tested": False, "requires_sponsor": True},
        {"subclass_number": "203", "visa_name": "Emergency Rescue", "stream_name": "Emergency Rescue", "category": "Permanent", "base_cost_aud": 0.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "204", "visa_name": "Woman at Risk", "stream_name": "Woman at Risk", "category": "Permanent", "base_cost_aud": 0.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "866", "visa_name": "Protection", "stream_name": "Protection", "category": "Permanent", "base_cost_aud": 45.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "785", "visa_name": "Temporary Protection", "stream_name": "Temporary Protection", "category": "Temporary", "base_cost_aud": 45.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "790", "visa_name": "Safe Haven Enterprise", "stream_name": "Safe Haven Enterprise", "category": "Temporary", "base_cost_aud": 45.00, "points_tested": False, "requires_sponsor": False},
        {"subclass_number": "851", "visa_name": "Resolution of Status", "stream_name": "Resolution of Status", "category": "Permanent", "base_cost_aud": 0.00, "points_tested": False, "requires_sponsor": False}
    ]

with open('visa_catalogue.json', 'w') as f:
    json.dump(get_visa_data(), f, indent=4)
